name: Postman Test and Testamat Report
on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 18 * * 3' # Runs every Wednesday at 7:30pm
    - cron: '30 18 * * 5' # Runs every Friday at 7:30pm
    - cron: '0 20 * * 0' # Runs every Sunday at 8:00pm

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install newman and testamat reporter
        run: |
          npm install -g newman newman-reporter-testamat
          echo "Newman and testamat reporter installed."
      
      - name: Run Postman tests with Testamat
        if: always()
        continue-on-error: true
        run: |
          newman run Postman-Collections/Postman-Collections.json --reporters cli,testamat \
          --reporter-testamat-endpoint ${{ secrets.TESTAMAT_URL }} \
          --reporter-testamat-project ${{ secrets.TESTAMAT_PROJECT }} \
          --reporter-testamat-token ${{ secrets.TESTAMAT_TOKEN }} \
          --reporter-testamat-launch "Postman API Tests"
          echo "Postman tests run with Testamat."

      - name: Notify Slack
        if: github.event_name == 'schedule'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: 'C070KUKPDLZ'
          SLACK_MESSAGE: |
            Paybox-360 - API Quality Readiness
            Contributors - Gambo Usman
            Status: ${{ job.status }}
            Testamat Report URL: ${{ secrets.TESTAMAT_REPORT_URL }}
